name: braucoe
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '^3.1.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_nav_bar: ^5.0.6
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_otp_text_field: ^1.1.1
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.1
  screenshot: ^2.1.0
  file_utils: ^1.0.1
  path_provider: ^2.1.1
  pdf: ^3.10.4
  flutter_svg: ^2.0.9
  firebase_storage: ^11.4.1
  file_saver: ^0.2.9
  firebase_core: ^2.21.0
  provider: ^6.0.5
  go_router: ^12.1.3
  crypto: ^3.0.3
  dio: ^5.4.0
  device_preview: ^1.1.0
  flutter_svg_provider: ^1.0.7
  emoji_picker_flutter: ^2.0.0
  encrypt: ^5.0.3
  cloud_firestore: ^4.15.4
  intl: ^0.18.1
  file_picker: ^6.1.1
  uuid: ^4.3.3
  flutter_map: ^6.1.0
  location: ^5.0.3
  latlong2: ^0.9.0
  label_marker: ^1.0.1
  flutter_gemini: ^2.0.3
  envied:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  envied_generator:
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LibreFranklin-Regular
      fonts:
        - asset: assets/fonts/LibreFranklin-Regular.ttf
    - family: LibreFranklin-Bold
      fonts:
        - asset: assets/fonts/LibreFranklin-Bold.ttf
    - family: LibreFranklin-Light
      fonts:
        - asset: assets/fonts/LibreFranklin-Light.ttf
    - family: LibreFranklin-SemiBold
      fonts:
        - asset: assets/fonts/LibreFranklin-SemiBold.ttf
    - family: LibreFranklin-Medium
      fonts:
        - asset: assets/fonts/LibreFranklin-Medium.ttf
    - family: AIChat
      fonts:
        - asset: assets/fonts/AIChat.ttf
    - family: Map
      fonts:
        - asset: assets/fonts/Map.ttf